apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.name }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{- printf " %s-role\n" .Values.rbac.name | trunc 63 }}
rules:
{{- range $item := .Values.rbac.rules }}
- apiGroups:
  {{- toYaml $item.apiGroups | nindent 2 }}
  resources:
  {{- toYaml $item.resources| nindent 2 }}
  verbs:
  {{- toYaml $item.verbs| nindent 2 }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{- printf " %s-rolebinding\n" .Values.rbac.name | trunc 63 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{- printf " %s-role" .Values.rbac.name | trunc 63 }}
  apiGroup: rbac.authorization.k8s.io
